### ISSUE TITLE
Serving app with Node.JS doesn't appear to be functioning

### ISSUE THREAD

**Issue by SouthernWolf95** [sh-dv/hat.sh#3]
When trying to serve the app with Node.JS, as opposed to use Browserify, the app crashes and gives the following error log

```
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '/home/username/hat.sh/app.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

```

I tried this both before and after installing Browserify. The Browserify version works perfectly and as expected. Do you have any idea why this might be occurring? 

I am on Linux, using PopOS (an Ubuntu/Debian based distro) version 19.04. I can confirm the Browserify process is flawless on Linux, so feel free to add that to your description! :)

**Comment by sh-dv** [comment]
hey, it's better to use browserify to bundle the js file , however WebPack js can also bundle this js file.
i tried to stay in a static app as much as possible, going at it with node js i think it would be something like this 👍 
`var express = require("express");
const http = require('http');
var app = express();

app.use(express.static(__dirname));
app.use('/css', express.static(__dirname + '/src/css'));
app.use('/js', express.static(__dirname + '/src/js'));
app.use('/assets', express.static(__dirname + '/public/assets'));
 
const server = http.createServer(app);
server.listen(3000);
console.log('listening on port 3000');`

i think in this case you have to create a app.js file in the main directory and then  `node app.js` from the terminal, i didn't have time to check these , when i'm free i'm gonna make sure it does, the issue is still open.

**Comment by SouthernWolf95** [comment]
Ah ok, cool! That makes sense as I didn't see an ```app.js``` file in the folder. I do also agree the Browserify option is best, but the reason I asked is cause I'm planing on forking this and adding an Electron shell to make it a stand-alone app for people that would rather use it that way! :)

**Comment by sh-dv** [comment]
Cool! , I have already used Electron js to make the app available for desktops, it's gonna be uploaded very very soon.

**Comment by sh-dv** [comment]
But u go fork it and do it , Maybe yours will be better and then i'm gonna merge it to the main repository.
