### ISSUE TITLE
Npm error, can not run - Ubuntu 20.04.3 LTS

### ISSUE THREAD

**Issue by scriptzteam** [sh-dv/hat.sh#46]
Any hint on how to fix this? Thanks

**lsb_release -a**
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
```

**npm run start**
```
> hat.sh@2.3.0 start /root/hat.sh
> next start -p 3991

ready - started server on 0.0.0.0:3991, url: http://localhost:3991
(node:56993) UnhandledPromiseRejectionWarning: ReferenceError: TextEncoder is not defined
    at Object.<anonymous> (/root/hat.sh/node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-writer.browser.production.min.server.js:9:95)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/root/hat.sh/node_modules/next/dist/compiled/react-server-dom-webpack/writer.browser.server.js:4:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
(node:56993) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:56993) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
error - Failed to load next.config.js, see more info here https://nextjs.org/docs/messages/next-config-error
Error: Not supported
    at Object.loadConfig [as default] (/root/hat.sh/node_modules/next/dist/server/config.js:399:74)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hat.sh@2.3.0 start: `next start -p 3991`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hat.sh@2.3.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
debug.log
```

**cat debug.log**
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'start' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle hat.sh@2.3.0~prestart: hat.sh@2.3.0
6 info lifecycle hat.sh@2.3.0~start: hat.sh@2.3.0
7 verbose lifecycle hat.sh@2.3.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle hat.sh@2.3.0~start: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/hat.sh/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle hat.sh@2.3.0~start: CWD: /root/hat.sh
10 silly lifecycle hat.sh@2.3.0~start: Args: [ '-c', 'next start -p 3991' ]
11 silly lifecycle hat.sh@2.3.0~start: Returned: code: 1  signal: null
12 info lifecycle hat.sh@2.3.0~start: Failed to exec start script
13 verbose stack Error: hat.sh@2.3.0 start: `next start -p 3991`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid hat.sh@2.3.0
15 verbose cwd /root/hat.sh
16 verbose Linux 5.4.0-91-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "start"
18 verbose node v10.19.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error hat.sh@2.3.0 start: `next start -p 3991`
22 error Exit status 1
23 error Failed at the hat.sh@2.3.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by sh-dv** [comment]
Look like you are running an old version of node.js. It's preferred to use the latest version (16).
check your version using this command `node -v`

**Comment by scriptzteam** [comment]
Just for anyone with the same error.

https://github.com/nvm-sh/nvm#install--update-script
nvm install 16.3.0

I also needed
npm install -g agentkeepalive --save
npm install -g npm@8.3.0

All build & run then ok :)
